version: "3.7"

services:
  envoy:
    image: envoyproxy/envoy:v1.13.1
    depends_on:
      - ping-grpc
    expose:
      - "10001"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  ping-grpc:
    image: golang:1.13
    working_dir: /go/github.com/socialpoint/istio-grpc-http1-reverse-bridge/services/ping-grpc
    volumes:
      - .:/go/github.com/socialpoint/istio-grpc-http1-reverse-bridge/services/ping-grpc
    expose:
      - "10005"
    command: go run main.go

  test:
    image: golang:1.13
    depends_on:
      - ping-grpc
      - envoy
    working_dir: /go/github.com/socialpoint/istio-grpc-http1-reverse-bridge/services/ping-grpc
    volumes:
      - .:/go/github.com/socialpoint/istio-grpc-http1-reverse-bridge/services/ping-grpc
    entrypoint: make test
