version: "3.7"

services:
  ping-http:
    image: golang:1.13
    expose:
      - "8888"
    ports:
      - "8888:8888"
    working_dir: /go/github.com/socialpoint/istio-grpc-http1-reverse-bridge/services/ping-grpc
    volumes:
      - .:/go/github.com/socialpoint/istio-grpc-http1-reverse-bridge/services/ping-grpc
    command: go run main.go

  envoy:
    image: envoyproxy/envoy:v1.13.1
    depends_on:
      - ping-http
    expose:
      - "10000"
    ports:
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
