docker-login:
	docker build -t spmanueljurado/ping-http:latest .
.PHONY: build

docker-build:
	docker build -t spmanueljurado/ping-http:latest .
.PHONY: build

docker-push:
	 docker push spmanueljurado/ping-http:latest
.PHONY: docker-push

up:
	docker-compose up
.PHONY: up

